export enum UserRightEnum {
    ADMINISTRATOR = 'ADMINISTRATOR',
    CATEGORY_MANAGER = 'CATEGORY_MANAGER',
    ARTICLE_MANAGER = 'ARTICLE_MANAGER',
    EMAIL_NOTIFICATION_MANAGER = 'EMAIL_NOTIFICATION_MANAGER',
    NETWORK_MANAGER = 'NETWORK_MANAGER',
    USER_MANAGER = 'USER_MANAGER',
}
