export enum UserActionEnum {
    VIEW_DASHBOARD = 'VIEW_DASHBOARD',
    UPDATE_DASHBOARD = 'UPDATE_DASHBOARD',
    VIEW_USER = 'VIEW_USER',
    ADD_USER = 'ADD_USER',
    DELETE_USER = 'DELETE_USER',
    EDIT_USER_MAIN_INFORMATION = 'EDIT_USER_MAIN_INFORMATION',
    EDIT_USER_RIGHT_INFORMATION = 'EDIT_USER_RIGHT_INFORMATION',
    TEST_EXCLUDED_ACTION = 'TEST_EXCLUDED_ACTION',
}
